name: health_dashboard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  google_fonts: ^6.3.2
  intl: ^0.20.2
  provider: ^6.1.5+1
  skeletonizer: ^2.1.0+1
  syncfusion_flutter_charts: ^31.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/data/journals.json
    - assets/data/user_data.json
    - assets/images/icons/
